export enum FilterActionTypes {
  RESET_FILTERS = "RESET_FILTERS",
  SET_GENRES = "SET_GENRES",
  SET_COUNTRIES = "SET_COUNTRIES",
  SET_YEARS = "SET_YEARS",
  SET_RATING = "SET_RATING",
  SET_SCORE = "SET_SCORE",
  SET_ACTORS = "SET_ACTORS",
  SET_DIRECTORS = "SET_DIRECTORS",
}
