export const FILTERS_ACTIONS = {
  RESET_FILTERS: "RESET_FILTERS",
  SET_GENRES: "SET_GENRES",
  SET_COUNTRIES: "SET_COUNTRIES",
  SET_YEARS: "SET_YEARS",
  SET_RATING: "SET_RATING",
  SET_SCORE: "SET_SCORE",
  SET_ACTORS: "SET_ACTORS",
  SET_SORT: "SET_SORT",
  SET_DIRECTORS: "SET_DIRECTORS",
  SET_FILTERS_RESULTS: "SET_FILTERS_RESULTS",
  GET_FILTERS_ERROR: "GET_FILTERS_ERROR",
};
