export const DATA_BANNER = {
  GET_DATA_BANNER: "GET_DATA_BANNER",
  GET_DATA_BANNER_START: "REQUEST_BANNER_START",
  GET_DATA_BANNER_SUCCESS: "REQUEST_BANNERS_SUCCESS",
  GET_DATA_BANNER_FAIL: "GET_DATA_BANNER_FAIL",
};
