export const DATA_HOME_PAGE = {
  GET_DATA_HOME_PAGE: "GET_DATA_HOME_PAGE",
  GET_DATA_HOME_PAGE_START: "GET_DATA_HOME_PAGE_START",
  GET_DATA_HOME_PAGE_SUCCESS: "GET_DATA_HOME_PAGE_SUCCESS",
  GET_DATA_HOME_PAGE_FAIL: "GET_DATA_HOME_PAGE_FAIL",
};
