export const DATA_TOP_MOVIES = {
  GET_DATA_TOP_MOVIES: "GET_DATA",
  GET_DATA_TOP_MOVIES_START: "GET_DATA_START",
  GET_DATA_TOP_MOVIES_SUCCESS: "GET_DATA_SUCCESS",
  GET_DATA_TOP_MOVIES_FAIL: "GET_DATA_FAIL",
};
