export const MOVIE_DATA = {
  GET_MOVIE_DATA: "GET_MOVIE_DATA",
  GET_MOVIE_DATA_START: "GET_MOVIE_DATA_START",
  GET_MOVIE_DATA_SUCCESS: "GET_MOVIE_DATA_SUCCESS",
  GET_MOVIE_DATA_FAIL: "GET_MOVIE_DATA_FAIL",
};
