export const DATA_MOVIE = {
  GET_DATA_MOVIE: "GET_DATA_MOVIE",
  GET_DATA_MOVIE_START: "GET_DATA_MOVIE_START",
  GET_DATA_MOVIE_SUCCESS: "GET_DATA_MOVIE_SUCCESS",
  GET_DATA_MOVIE_FAIL: "GET_DATA_MOVIE_FAIL",
};
