import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "./Home.module.scss";
import Catalog from "@/components/Catalog";
import Banner from "@/components/Banner";
import CardMovie from "@/components/CardMovie";
const inter = Inter({ subsets: ["latin"] });

const data = {
  title: "1. Возвращение в Простоквашино. Часть 1",
  text: "В жизни дяди Федора произошли серьезные перемены. У него появилась маленькая сестренка – Вера Павловна. И потому мама и папа уделяют сыну совсем мало внимания. А ему, между тем, требуется поддержка родителей. Дядя Федор получает известие из Простоквашино. На ферме Матроскина завелся таинственный грызун, который вывел из строя систему электроснабжения. Холодильник перестал работать, все молоко скисло. А Шарик вместо того, чтобы охранять дом, стал модным блогером. Дядя Федор спешит на помощь.",
  type: "detailed",
  img: "https://cdn.iz.ru/sites/default/files/styles/900x506/public/news-2019-03/8_0.jpg?itok=52JttP6Z",
};
const Home = () => {
  return (
    <>
      <Head>
        <title>IVI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <div className={styles.continue_browsing}>
        <CardMovie
          title={data.title}
          type={data.type}
          text={data.text}
          img={data.img}
        />
      </div>
      <Catalog />
    </>
  );
};
export default Home;
