export const DATA_COMMENTS = {
  SEND_COMMENT: "SEND_COMMENT",
  SEND_COMMENT_START: "SEND_COMMENT_START",
  SEND_COMMENT_SUCCESS: "SEND_COMMENT_SUCCESS",
  SEND_COMMENT_FAIL: "SEND_COMMENT_FAIL",
} as const;
