export const REGISTRATION_DATA = {
  GET_REGISTRATION_DATA: "GET_REGISTRATION_DATA",
  GET_REGISTRATION_DATA_START: "GET_REGISTRATION_DATA_START",
  GET_REGISTRATION_DATA_SUCCESS: "GET_REGISTRATION_DATA_SUCCESS",
  GET_REGISTRATION_DATA_FAIL: "GET_REGISTRATION_DATA_FAIL",
};
