export const AUTH_DATA = {
  GET_AUTH_DATA: "GET_AUTH_DATA",
  GET_AUTH_DATA_START: "GET_AUTH_DATA_START",
  GET_AUTH_DATA_SUCCESS: "GET_AUTH_DATA_SUCCESS",
  GET_AUTH_DATA_FAIL: "GET_AUTH_DATA_FAIL",
  CLEAR_AUTH_DATA: "CLEAR_AUTH_DATA",
};
