export const MOVIES_ACTIONS = {
  GET_MOVIES_START: "GET_MOVIES_START",
  GET_MOVIES_DATA: "GET_MOVIES_DATA",
  GET_MOVIES_ERROR: "GET_MOVIES_ERROR",
  WATCH_EDIT_GENRE: "WATCH_EDIT_GENRE",
  EDIT_GENRE: "EDIT_GENRE",
};
