export const MOVIES_ACTIONS = {
  GET_MOVIES_START: "GET_MOVIES_START",
  GET_MOVIES: "GET_MOVIES",
  GET_MOVIES_DATA: "GET_MOVIES_DATA",
  GET_MOVIES_DATA_ALL: "GET_MOVIES_DATA_ALL",
  GET_MOVIES_ERROR: "GET_MOVIES_ERROR",
  EDIT_GENRES: "EDIT_GENRES",
};
